apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-frontend
  namespace: currency-exchange
  labels:
    app: currency-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-frontend
  template:
    metadata:
      labels:
        app: currency-frontend
    spec:
      containers:
      - name: currency-frontend
        image: registry.cn-hangzhou.aliyuncs.com/your-namespace/currency-exchange-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: currency-frontend-service
  namespace: currency-exchange
spec:
  selector:
    app: currency-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer