apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: currency-data-pvc
  namespace: currency-exchange
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: alicloud-disk-ssd